### ISSUE TITLE
[hub-mirror] 请求执行任务，成功案例

### ISSUE THREAD

**Issue by togettoyou** [togettoyou/hub-mirror#1]
{
    "hub-mirror": [
        "gcr.io/google-samples/microservices-demo/emailservice:v0.3.5",
        "gcr.io/google-samples/microservices-demo/checkoutservice:v0.3.5",
        "gcr.io/google-samples/microservices-demo/recommendationservice:v0.3.5",
        "gcr.io/google-samples/microservices-demo/frontend:v0.3.5",
        "gcr.io/google-samples/microservices-demo/paymentservice:v0.3.5",
        "gcr.io/google-samples/microservices-demo/productcatalogservice:v0.3.5",
        "gcr.io/google-samples/microservices-demo/cartservice:v0.3.5",
        "gcr.io/google-samples/microservices-demo/loadgenerator:v0.3.5",
        "gcr.io/google-samples/microservices-demo/currencyservice:v0.3.5",
        "gcr.io/google-samples/microservices-demo/shippingservice:v0.3.5",
        "gcr.io/google-samples/microservices-demo/adservice:v0.3.5"
    ]
}

**Comment by HubWu42** [comment]
ghcr.io/yangchuansheng/ip_derper

**Comment by wang-xiaowu** [comment]
ghcr.io/aquasecurity/trivy-db

**Comment by class-newking** [comment]
quay.io/coreos/etcd:v3.5.25
