### ISSUE TITLE
[hub-mirror] 请求执行任务

### ISSUE THREAD

**Issue by LucienShui** [togettoyou/hub-mirror#1170]
{
    "hub-mirror": [
        "nvcr.io/nvidia/pytorch:23.08-py3"
    ]
}

**Comment by LucienShui** [comment]
Error: No space left on device : '/home/runner/runners/2.309.0/_diag/pages/44d2a871-0074-4234-9c46-75210dc7693a_278ff417-6f7b-54eb-f370-240af96e13dd_1.log'

@togettoyou 貌似默认的机器没有那么大的磁盘，难顶，这种是不是就无解了？（除了加钱）

**Comment by togettoyou** [comment]
科学上网看能不能拉下来吧
github action有限制的

**Comment by togettoyou** [comment]
镜像有多大

**Comment by LucienShui** [comment]
> 镜像有多大

8G，我看了下官网的文档貌似是 7G 的空间，略极限了点，哈哈。

非常感谢。
