### ISSUE TITLE
docker hub 现在貌似不能使用密码直接登录

### ISSUE THREAD

**Issue by zeromake** [togettoyou/hub-mirror#54]
要去 docker hub 后台的 [security](https://hub.docker.com/settings/security) 生成一个有写入权限的 token.
用账号密码会无法认证

**Comment by togettoyou** [comment]
#55 我测试了一下，应该还是 OK 的

**Comment by zeromake** [comment]
> #55 我测试了一下，应该还是 OK 的

可能是我的 docker hub 账号有什么安全设置吧，可以补充一下到说明无法使用密码认证的可以去生成token
